### ISSUE TITLE
S25: As a player, I want to get XP from every round. The collected points get converted to XP and if I did something special (e.g. fast correct guess, first place, surpass points threshold), I want to get a trophy that will be permanently added to my profile.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#25]
- [x] After every game points get converted to XP and added to the profile.
- [ ] If something special was achieved, a trophy is awarded and added to the profile.
- [ ] These chances to the profile need to be permanent.
Task List (front & back):
- [ ] convert total points of a player to XP after a game and store them in his data base entry (front)
- [ ] check for special cases in a game where throphies need to be rewarded, show them to the user and store them in the data base (front)
- [x] provide necessary REST methods for storing and updating XP and trophies

**Comment by dominiqueheller** [comment]
The trophy system was not implemented, but the xp and level was
