### ISSUE TITLE
S5: As a logged in user, I want to be able to change the information in my user profile.

### ISSUE THREAD

**Issue by FloMatt12** [sopra-fs24-group-43/server#5]
- [x] A user can also edit information that other users cannot see, such as their password.
- [x] #119
- [x] sopra-fs24-group-43/client#182
- [x] sopra-fs24-group-43/client#217
Task List (front& back):
- [x] provide button enable editing the profile info (front)
- [x] provide input fields for user to pass in data (front)
- [x] implement REST method for updating Data base enteries

**Comment by RobinStirnimann** [comment]
improved in https://github.com/sopra-fs24-group-43/server/commit/03db24bf5a14cd225eb1cc33ef2007f0565ce5d3
